hfms-server:
  fullnameOverride: "hfms-server"

  service:
    type: ClusterIP
    port: 9000
  
  env:
    HOST : hfms-db
    PORT : 3306
    USERNAME : root
    PASSWORD : pass
    DATABASE : hfms
    URL : http://hfms-proxy.default.svc.cluster.local:4443
    SERVER_PATH: /Users/ashokkumar/Desktop/HFMS-TRAD/server
  
  nginx:
    fullnameOverride: "hfms-nginx"

    service:
      type: ClusterIP
      port: 80

    env : 
      CONFIG_PATH: /Users/ashokkumar/Desktop/HFMS-TRAD/helm-charts/main-chart/charts/hfms-server/charts/nginx/configs/nginx.conf
      SERVER_PATH: /Users/ashokkumar/Desktop/HFMS-TRAD/server

hfms-api:
  fullnameOverride: "hfms-api"

  service:
    type: ClusterIP
    port: 3002
  
  env:
    HOST : hfms-db
    PORT : 3306
    USERNAME : root
    PASSWORD : pass
    DATABASE : hfms
  
hfms-db:
  fullnameOverride: "hfms-db"

  service:
    type: ClusterIP
    port: 3306

  env:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: hfms
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

hfms-admin:
  fullnameOverride: "hfms-admin"

  service:
    type: ClusterIP
    port: 8080


oauth2-proxy:

  fullnameOverride: "hfms-proxy"

  # Oauth client configuration specifics
  config:
    # Add config annotations
    annotations: {}
    # OAuth client ID
    clientID: "880386795823-olrdr7047el8skubcoaa02avc13lql6b.apps.googleusercontent.com"
    # OAuth client secret
    clientSecret: "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"
 
    cookieSecret: "5S5wk5A5O6MkKfZZ"
  
    cookieName: "oauth2_proxy"
    
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [
      "http://hfms-nginx.default.svc.cluster.local:80",
      "http://hfms-api.default.svc.cluster.local:3002/requests"]
      provider = "oidc"
      provider_display_name="Asgardeo"
      reverse_proxy = false
      redirect_url = "https://hfms.proxy.com/oauth2/callback"
      oidc_issuer_url = "https://accounts.google.com"
      scope= "openid email"
      skip_auth_regex="/hospitalDashoard.php,/assets/*"
      skip_provider_button=true
      pass_access_token=true
      pass_authorization_header=true
      pass_basic_auth=true
      pass_user_headers=true

  service:
    type: ClusterIP
    portNumber: 4443
    appProtocol: http
  
